[package]
name = "reqwest-example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eyre = "0.6.5"
reqwest = "0.11.7"
tokio = { version = "1.14.0", features = ["full"] }
